Update md guidance to include all current recommendations
MicrosoftDocs/PowerShell-Docs pull request #11046
Opened 2024-04-23 21:44 UTC by sdwheeler

# PR Summary

Update md guidance to include all current recommendations

- Fixes AB#248103

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2024-04-23 22:32 UTC, mikefrobbins requested changes
See my comments.

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +Code blocks are used for command example, multi-line code samples, query languages, and outputs.
```suggestion
Code blocks are used for command examples, multi-line code samples, query languages, and outputs.
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +Never use indentation because it's too easy to get wrong and it may be hard for another writer to
```suggestion
Never use indentation because it's too easy to get wrong and it may be difficult for another writer to
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +case-sensitive, but except for a few special cases, you should use lowercase.
```suggestion
case-sensitive, but you should use lowercase except for a few special cases.
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +  highlighting.
```suggestion
- Code fences without tags can be used for syntax blocks or other types of content where syntax
highlighting is not required.
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
>  tutorial for Markdown, but list specific rules and best practice for Markdown in the PowerShell
```suggestion
tutorial for Markdown, but lists specific rules and best practices for Markdown in the PowerShell
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
>  This is a list that contain child elements under a bullet item.
```suggestion
This is a list that contains child elements under a bullet item.
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +reflowed to fit within the 100-character line limit, and are more accessible for uses that use
```suggestion
reflowed to fit within the 100-character line limit, and are more accessible for users that use
```

2024-04-23 22:32 UTC, mikefrobbins commented on reference/docs-conceptual/community/contributing/general-markdown.md
> +This examples renders as:
```suggestion
This example renders as:
```

2024-04-23 22:41 UTC, mikefrobbins commented
A couple of additional items I wasn't able to comment on in the PR:

- Change _listed_ to _list_ in this sentence under **Ordered lists**: _All items in a numbered listed should use the number 1. rather than incrementing each item._
- Add the word _from_ between _article_ and _affecting_ in this sentence under **Images**: _This prevents a change to an image in one article affecting another article._

2024-04-24 13:23 UTC, closed without merging

2024-04-24 13:36 UTC, michaeltlombardi approved these changes