Corrected the names referring to WDAC to use App Control
MicrosoftDocs/PowerShell-Docs pull request #11481
Opened 2024-10-18 07:22 UTC by HotCakeX

# PR Summary

It's no longer called WDAC or Windows Defender Application Control. It's called App Control for Business. Microsoft has updated the relevant docs to use the correct name, i fixed this document to be aligned with them.

https://learn.microsoft.com/en-us/windows/security/application-security/application-control/app-control-for-business/appcontrol

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2024-10-18 14:48 UTC, sdwheeler commented
@vinaypamnani-msft Can you review this PR?

2024-10-21 15:40 UTC, vinaypamnani-msft requested changes
Added a couple of suggestions, rest looks good.

2024-10-21 15:40 UTC, vinaypamnani-msft commented on reference/docs-conceptual/security/app-control/how-wdac-works.md
> +description: This article explains how App Control works to secure PowerShell and the restrictions it imposes.
```suggestion
description: This article explains how App Control for Business works to secure PowerShell and the restrictions it imposes.
```

2024-10-21 15:40 UTC, vinaypamnani-msft commented on reference/docs-conceptual/security/app-control/how-wdac-works.md
> +title: How App Control works with PowerShell
```suggestion
title: How App Control for Business works with PowerShell
```

2024-10-21 15:40 UTC, vinaypamnani-msft commented on reference/docs-conceptual/security/app-control/how-wdac-works.md
> +PowerShell detects both **AppLocker** and **Application Control for Business** system
```suggestion
PowerShell detects both **AppLocker** and **App Control for Business** system
```

2024-10-21 15:51 UTC, merged

2024-10-21 16:47 UTC, HotCakeX commented
Thank you