Fix wording
MicrosoftDocs/PowerShell-Docs pull request #7074
Opened 2020-12-22 13:21 UTC by dawedawe

# PR Summary

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

## PR Checklist

- [ ] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [ ] PR has a meaningful title
- [ ] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2020-12-22 13:22 UTC, opbld33 commented
Docs Build status updates of commit _[1af497e](https://github.com/dawedawe/PowerShell-Docs/commits/1af497e9e97552ed56189cedbe12123e788052d1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2&branch=pr-en-us-7074) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C22%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202012221321103923-7074%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bqOKNVG5pCEIKJgQXo68jtxeywUlDSvQ4RkaMqiSz4I%3D&st=2020-12-22T13%3A17%3A49Z&se=2021-01-22T13%3A22%3A49Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-23 18:25 UTC, chasewilson approved these changes

2020-12-23 18:27 UTC, chasewilson requested changes
Thank you for the contribution! This only changes once version. Would you be able to make the same changes to all versions before we merge this in?

2020-12-23 19:26 UTC, opbld33 commented
Docs Build status updates of commit _[522a561](https://github.com/dawedawe/PowerShell-Docs/commits/522a5610e4f5d7430d5b8a6f41e1df3958c1a295)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.1&branch=pr-en-us-7074) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2&branch=pr-en-us-7074) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C23%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202012231924303544-7074%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=PWrivLErh6Sf6Hg3hFfI5WLaaZWkdlPQpQ5kVkIL7iY%3D&st=2020-12-23T19%3A21%3A03Z&se=2021-01-23T19%3A26%3A03Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-23 19:27 UTC, opbld31 commented
Docs Build status updates of commit _[638b0e0](https://github.com/dawedawe/PowerShell-Docs/commits/638b0e0144e315d07057f13b39092363400ee7f0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7&branch=pr-en-us-7074) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.1&branch=pr-en-us-7074) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2&branch=pr-en-us-7074) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C23%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202012231925299841-7074%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8WBInRdWQcltod%2BhZ4vqwrzoHzTV2WuuJeshnvpDDgU%3D&st=2020-12-23T19%3A22%3A46Z&se=2021-01-23T19%3A27%3A46Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-23 19:29 UTC, opbld33 commented
Docs Build status updates of commit _[a1d192c](https://github.com/dawedawe/PowerShell-Docs/commits/a1d192c2aa35785648a29b4dbd8233c9002d50ff)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/5.1/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-5.1&branch=pr-en-us-7074) (powershell-5.1) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.0/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7&branch=pr-en-us-7074) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.1/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.1&branch=pr-en-us-7074) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md](https://github.com/dawedawe/PowerShell-Docs/blob/patch-1/reference/7.2/Microsoft.PowerShell.Core/About/about_Signing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_signing?view=powershell-7.2&branch=pr-en-us-7074) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C12%5C23%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202012231926426829-7074%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=f80uO9wyray83m6aOCBDkHs0NnbMFmS76KVxwf1iqk0%3D&st=2020-12-23T19%3A24%3A36Z&se=2021-01-23T19%3A29%3A36Z&sp=r).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching in the <a href="https://review.docs.microsoft.com/en-us/search/?search=&amp;category=All&amp;scope=help-docs&amp;category=All&amp;branch=master">Docs contributor and Admin Guide</a></li><li>See the <a href="https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master">frequently asked questions</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2020-12-23 19:36 UTC, dawedawe commented
> 
> 
> Thank you for the contribution! This only changes once version. Would you be able to make the same changes to all versions before we merge this in?

Sure, should have done this from the start, sorry.

2020-12-24 05:45 UTC, Mellbabe approved these changes

2020-12-24 05:48 UTC, Mellbabe approved these changes

2020-12-25 01:54 UTC, chasewilson approved these changes

2020-12-25 01:55 UTC, merged