Sort instructions from newest to oldest versions
MicrosoftDocs/PowerShell-Docs pull request #7286
Opened 2021-02-22 09:49 UTC by Tbohunek

# PR Summary

I suggest to sort steps from newest to oldest. Gotta lead by example and promote latest versions. 😉 

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [x] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Sample scripts
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [ ] Preview content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [ ] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2021-02-22 15:01 UTC, sdwheeler commented
@SteveL-MSFT Can we get someone to review these changes?

2021-02-22 18:28 UTC, TravisEz13 requested changes

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Ubuntu `19.10` (via Snap package)
```suggestion
- Ubuntu `19.10` (via Snap package)
```
This is not officially supported.

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- openSUSE Leap `15`
leap is not officially supported

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- openSUSE `42.3`
This is EOL and no longer officially supported.

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Fedora `30`/`29`/`28`
These are all EOF and thus, no longer officially supported.

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Alpine `3.10`/`3.9`
3.9 is EOL and thus, no longer officially supported.

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Debian `10`/`9`/`8`
8 is EOL and thus, no longer officially supported.

2021-02-22 18:28 UTC, TravisEz13 commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Fedora `30`
30 is EOL and thus, no longer officially supported.

2021-02-22 20:24 UTC, adityapatwardhan commented on reference/docs-conceptual/install/Installing-PowerShell-Core-on-Linux.md
> +- Alpine `3.11`+ (including ARM64)
Alpine ARM64 is not supported yet.

2021-02-22 21:23 UTC, Tbohunek commented
Just for the record, I only reordered the text, suggesting approach to be taken generally.
Maybe cleanup in terms of actually supported versions should be handled separately?

2021-02-23 15:29 UTC, sdwheeler commented
@Tbohunek Thanks for the contribution but we can't take these changes as submitted.

2021-02-23 15:29 UTC, closed without merging

2021-02-23 19:53 UTC, Tbohunek commented
@sdwheeler cool, fine with me, just not sure what you mean by "can't take these changes as submitted". Did I miss anything, shall I adjust the proposal, or is this type of contribution not desired? Thanks.

2021-02-23 20:36 UTC, sdwheeler commented
I agree that the article needs to be updated. But too many of the changes are incorrect. I suggest that you open an issue describing what you think needs to be corrected or changed. I will work with the PowerShell team to get the correct information into the article.