Add examples for + and minus, fix unary -
MicrosoftDocs/PowerShell-Docs pull request #8281
Opened 2021-10-30 20:31 UTC by yecril71pl

# PR Summary

Fix: the result of unary operator `-` is not always negative.
About unary operator `+`.
Addition and subtraction of enumerated values.
Minor editing corrections.

## PR Context

Select the area of the Table of Contents containing the documents being changed.

**Conceptual content**
- [ ] Overview and Install
- [ ] Learning PowerShell
  - [ ] PowerShell 101
  - [ ] Deep dives
  - [ ] Sample scripts
  - [ ] Remoting
- [ ] Release notes (What's New)
- [ ] Windows PowerShell
  - WMF, ISE, release notes, etc.
- [ ] DSC articles
- [ ] Community resources
- [ ] Gallery articles
- [ ] Scripting and development
  - [ ] Language Spec
  - [ ] Legacy SDK

**Cmdlet reference & about_ topics**
- [X] Preview content
- [X] Version 7.1 content
- [X] Version 7.0 content
- [X] Version 5.1 content

## PR Checklist

- [X] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [X] PR has a meaningful title
- [X] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [ ] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**
  - If the PR is work in progress, please add the prefix `WIP:` or `[WIP]` to the beginning of the
    title and remove the prefix when the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2021-10-30 20:33 UTC, opbld32 commented
Docs Build status updates of commit _[1262780](https://github.com/yecril71pl/PowerShell-Docs/commits/12627802327c24bd060885860c8ee7c7c4aa4072)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C10%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202110302031347666-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-11-30T20%3A33%3A29Z&sr=b&sp=r&sig=fUGOXGFKrQSBmtlxv%2FmUuohr701YSp4J2InUx2alcLE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-12 17:21 UTC, sdwheeler commented
@yecril71pl Are you going to make the same changes to the other versions?

2021-11-12 17:24 UTC, yecril71pl commented
> @yecril71pl Are you going to make the same changes to the other versions?

Sure, as soon as you tell me they are OK.

2021-11-15 21:21 UTC, sdwheeler requested changes
Go ahead and copy the changes to all versions.

2021-11-15 21:45 UTC, opbld30 commented
Docs Build status updates of commit _[ac61b42](https://github.com/yecril71pl/PowerShell-Docs/commits/ac61b42d5ed8510d3334157debecf47b8aeef33d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202111152143142206-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T21%3A45%3A42Z&sr=b&sp=r&sig=NwVzNaLNBrChqJQCCinf7SC%2BYL9Bq8sZrtqP0F2w4cg%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 21:53 UTC, opbld30 commented
Docs Build status updates of commit _[cd3fede](https://github.com/yecril71pl/PowerShell-Docs/commits/cd3fedea7ed4cddb83e4733a452ad56ddc613415)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.2&branch=pr-en-us-8281) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202111152151395487-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T21%3A53%3A29Z&sr=b&sp=r&sig=SgaSD%2BK2X%2BhUIyE%2FZ9YDuIHlyyiCco%2FbUS%2BktXGHtWE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 22:03 UTC, opbld32 commented
Docs Build status updates of commit _[a98bbc2](https://github.com/yecril71pl/PowerShell-Docs/commits/a98bbc2ac792a3334a236b529290ddbe9c52d2a0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7&branch=pr-en-us-8281) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.2&branch=pr-en-us-8281) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202111152202062588-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T22%3A03%3A58Z&sr=b&sp=r&sig=roBc2htMM4KdV3%2BP7fb%2BG7diSKdIKpY6W8ibPkf1ie4%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 22:10 UTC, opbld33 commented
Docs Build status updates of commit _[09f310a](https://github.com/yecril71pl/PowerShell-Docs/commits/09f310ade7dc9617eac1c2944faa75b38ac0215d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-5.1&branch=pr-en-us-8281) (powershell-5.1) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7&branch=pr-en-us-8281) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.2&branch=pr-en-us-8281) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202111152208020521-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T22%3A10%3A12Z&sr=b&sp=r&sig=9hx2u%2BvFGLVB%2B4we0vTu6Ilwfx%2Fl6FV6gUXS2fdO68k%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-15 22:25 UTC, opbld32 commented
Docs Build status updates of commit _[0c65b5d](https://github.com/yecril71pl/PowerShell-Docs/commits/0c65b5d37c8b2b3f168e42fc6cd4091515ab9e13)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/5.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-5.1&branch=pr-en-us-8281) (powershell-5.1) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.0/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7&branch=pr-en-us-8281) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.1/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.1&branch=pr-en-us-8281) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md](https://github.com/yecril71pl/PowerShell-Docs/blob/patch-3/reference/7.2/Microsoft.PowerShell.Core/About/about_Arithmetic_Operators.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arithmetic_operators?view=powershell-7.2&branch=pr-en-us-8281) (powershell-7.2) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2021%5C11%5C15%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202111152223248429-8281%5Cworkflow_report.html?sv=2020-08-04&se=2021-12-16T22%3A25%3A05Z&sr=b&sp=r&sig=7JE%2FNT6k7zwq9SBYM5Tl%2BgvdD0yBEark%2B%2BrlGgYRL%2Bo%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=master">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2021-11-16 15:35 UTC, merged