(GH-8628) Note PSCustomObject Count Behavior
MicrosoftDocs/PowerShell-Docs pull request #8639
Opened 2022-03-08 23:32 UTC by michaeltlombardi

# PR Summary
This PR updates the documentation for `about_PSCustomObject` and `about_Arrays` in Windows PowerShell 5.1 to note the divergent behavior of objects created by casting a hashtable to `[pscustomobject]` which returns `$null` for the automatic **Count** and **Length** properties.

- Fixes #8628 

## PR Context

Check the boxes below to indicate the content affected by this PR.

**Repository or docset configuration**
- [ ] Repo documentation and configuration (.git/.github/.vscode etc.)
- [ ] Docs build files (.openpublishing.* and build scripts)
- [ ] Docset configuration (docfx.json, mapping, bread, module folder)

**Conceptual documentation**
- [ ] Files in docs-conceptual

**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.

- [ ] Preview content
- [ ] Version 7.2 content
- [ ] Version 7.1 content
- [ ] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**. If the PR is work in progress,
  please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
  the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2022-03-08 23:34 UTC, michaeltlombardi commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
> +
I am unsure of the wording here but I do feel it is useful to call out the behavior here as well as in `about_PSCustomObject` as it directly contradicts the stated documentation.

2022-03-08 23:34 UTC, opbld33 commented
Docs Build status updates of commit _[1995141](https://github.com/michaeltlombardi/PowerShell-Docs/commits/1995141706255e1d03f14f17ae7d9b9b9a7d4797)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8628/staging/pscustomobject-count/reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arrays?view=powershell-5.1&branch=pr-en-us-8639) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8628/staging/pscustomobject-count/reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_pscustomobject?view=powershell-5.1&branch=pr-en-us-8639) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C8%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203082332182137-8639%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-08T23%3A34%3A32Z&sr=b&sp=r&sig=RgUdW5SZyZQTXABRGVK4wi6%2BckVfvRQupBdzNbIoPJ0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 14:13 UTC, sdwheeler requested changes

2022-03-09 14:13 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md
> +**Hashtable** to `[pscustomobject]` returns `$null` in Windows PowerShell.
```suggestion
In Windows PowerShell, objects created by casting a **Hashtable** to
`[pscustomobject]` do not have the **Length** or **Count** properties.
Attempting to access these members returns `$null`.

For example:

```powershell
PS> $object = [PSCustomObject]@{key = 'value'}
PS> $object

key
---
value

PS> $object.Count
PS> $object.Length
```
```

2022-03-09 14:13 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md
> +> functionality.
```suggestion
> [!TIP]
In Windows PowerShell, objects created by casting a **Hashtable** to
`[pscustomobject]` do not have the **Length** or **Count** properties.
Attempting to access these members returns `$null`.
```

2022-03-09 15:41 UTC, opbld32 commented
Docs Build status updates of commit _[f8724bf](https://github.com/michaeltlombardi/PowerShell-Docs/commits/f8724bf55dc061e099d1935769d1413926f42b81)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8628/staging/pscustomobject-count/reference/5.1/Microsoft.PowerShell.Core/About/about_Arrays.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_arrays?view=powershell-5.1&branch=pr-en-us-8639) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8628/staging/pscustomobject-count/reference/5.1/Microsoft.PowerShell.Core/About/about_PSCustomObject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_pscustomobject?view=powershell-5.1&branch=pr-en-us-8639) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C9%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203091539326365-8639%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-09T15%3A41%3A52Z&sr=b&sp=r&sig=lfIpBP7No7%2BYCTMcO2jSQkitno7worEKpH1Gyto%2B8xc%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-09 16:53 UTC, sdwheeler approved these changes

2022-03-09 16:53 UTC, merged