WIP: (GH-8503) Add about_Module_Manifests
MicrosoftDocs/PowerShell-Docs pull request #8696
Opened 2022-03-28 18:44 UTC by michaeltlombardi

# PR Summary
Adds the `about_Module_Manifests` topic.

- Resolves #8503 

## PR Context

Check the boxes below to indicate the content affected by this PR.

**Repository or docset configuration**
- [ ] Repo documentation and configuration (.git/.github/.vscode etc.)
- [ ] Docs build files (.openpublishing.* and build scripts)
- [ ] Docset configuration (docfx.json, mapping, bread, module folder)

**Conceptual documentation**
- [ ] Files in docs-conceptual

**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.

- [x] Preview content
- [x] Version 7.2 content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [ ] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [ ] This PR is ready to merge and is not **Work in Progress**. If the PR is work in progress,
  please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
  the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2022-03-28 19:05 UTC, opbld33 commented
Docs Build status updates of commit _[788c607](https://github.com/michaeltlombardi/PowerShell-Docs/commits/788c607a7917f58d140ab35ab6a73cd10c780b52)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C28%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203281903435754-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-28T19%3A05%3A56Z&sr=b&sp=r&sig=jm7YPQVoROlTSCi9kUgOQkrJBHgFPBVyiZGW9Gq7L3Y%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-28 22:20 UTC, sdwheeler requested changes
Commit my review comments and taking a break. I will add more comments later.

2022-03-28 22:20 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +exported.
What about cdxml and xaml types, are their values exported differently? In script-based modules, you can use the `Export-ModuleMember` cmdlet.

So really, you mean that for exports defined in the manifest, the files containing the items to be exported must be listed in **RootModule** or **NestModules**.

2022-03-28 22:20 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +```
I am not sure that these are needed. It seems redundant to the bullet list above.

2022-03-29 13:44 UTC, opbld32 commented
Docs Build status updates of commit _[03eac14](https://github.com/michaeltlombardi/PowerShell-Docs/commits/03eac1433f83f5d494ce0db0a340410dff8277b6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203291342212080-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T13%3A44%3A18Z&sr=b&sp=r&sig=TyZ0QkbMOTo7MqM4mqoowh7HzkZtLjhMVieiVWlmgmY%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 18:16 UTC, sdwheeler requested changes
more comments

2022-03-29 18:16 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +```
Ditch the H4s. Make the description more imperative. Don't need to show all 4 possible combinations. Just explain that "Undefined is the same as `@('Desktop', 'Core')`.

An empty array is allowed. Do we know if that is the same as both? Or what does it mean to be 'none'?

2022-03-29 21:31 UTC, opbld30 commented
Docs Build status updates of commit _[3f6c0f3](https://github.com/michaeltlombardi/PowerShell-Docs/commits/3f6c0f3b507da72a6eb482c883b2fa26edc2da90)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) | [Details](#user-content-92b5232ef5698c5b5afe538709fa8fb4-9420c05b)

<a id="92b5232ef5698c5b5afe538709fa8fb4-9420c05b"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md)
 - **Line 207, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````
 - **Line 1478, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203292120491702-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T21%3A31%3A21Z&sr=b&sp=r&sig=w5%2BjrgXVtj6b8qHMIFu107mJwKABPFPEqrEKnH1Cexk%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 21:33 UTC, opbld32 commented
Docs Build status updates of commit _[eac3376](https://github.com/michaeltlombardi/PowerShell-Docs/commits/eac3376155e069cf84d8c0903f8ebc2e36890145)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) | [Details](#user-content-92b5232ef5698c5b5afe538709fa8fb4-9508fbb5)

<a id="92b5232ef5698c5b5afe538709fa8fb4-9508fbb5"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md)
 - **Line 207, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````
 - **Line 1478, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C29%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203292125372210-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-29T21%3A33%3A40Z&sr=b&sp=r&sig=XskOwnRMyMZ9e0jSrZ7YJm7yFnPCmPRT%2FIb%2FbtjmWt4%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-29 22:04 UTC, sdwheeler requested changes
Looking much better. Try to separate consecutive alert blocks.

2022-03-30 13:15 UTC, opbld33 commented
Docs Build status updates of commit _[bea7a4e](https://github.com/michaeltlombardi/PowerShell-Docs/commits/bea7a4eee2460e59a9a331202cbe99541e4360d1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :warning:Warning | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) | [Details](#user-content-92b5232ef5698c5b5afe538709fa8fb4-f0866b12)

<a id="92b5232ef5698c5b5afe538709fa8fb4-f0866b12"></a>
### [reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md)
 - **Line 207, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````
 - **Line 1478, Column 3**: **[Warning: file-not-found - [See documentation](https://review.docs.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: 'about_powershell_editions.md'.`````

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203301313066286-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T13%3A15%3A06Z&sr=b&sp=r&sig=bLjgwJZeSzkM3WsnWk4aRA%2BWOf4kH0Rf%2BAASpZGtL2c%3D).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Docs Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 14:04 UTC, opbld32 commented
Docs Build status updates of commit _[b4804bd](https://github.com/michaeltlombardi/PowerShell-Docs/commits/b4804bdec3de44dc206fe7264370db452ee17545)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203301401587966-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T14%3A04%3A09Z&sr=b&sp=r&sig=GeUXDTmA7RitKCsv26C8ukE6jUbh4ObDTXPQ%2BYtf5ZE%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 14:18 UTC, opbld32 commented
Docs Build status updates of commit _[92d4447](https://github.com/michaeltlombardi/PowerShell-Docs/commits/92d4447bfbff616f3de3bd818554799c1935cf42)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203301416202552-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T14%3A18%3A21Z&sr=b&sp=r&sig=MDlP%2BYGfHSfTfX3CION2kk7%2FPzfP4WsVCT97Dn%2FHEu0%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 14:28 UTC, sdwheeler requested changes

2022-03-30 14:28 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +settings to further restrict exported commands.
```suggestion
Any items that need to be exported from a nested module must exported by the
nested module using the `Export-ModuleMember` cmdlet or be listed in one of the
export properties:

- **FunctionsToExport**
- **CmdletsToExport**
- **VariablesToExport**
- **AliasesToExport**
```

2022-03-30 14:28 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +in the list of exported functions is exported.
```suggestion
in the list of exported functions are exported.
```

2022-03-30 14:28 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +nested modules export are available.
```suggestion
For example, when you import a module with the setting commented out, 
all functions in the root module and any nested modules are exported.
```

2022-03-30 14:28 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +nested modules export are available.
```suggestion
For example, when you import a module with this setting commented out, 
all cmdlets in the root module and any nested modules are exported.
```

2022-03-30 14:28 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +nested modules export are available.
```suggestion
For example, when you import a module with this setting commented out,
all variables in the root module and any nested modules are exported.
```

2022-03-30 14:48 UTC, michaeltlombardi commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +| **Required**          | For PowerShell Gallery |
```suggestion
| **Required**          | PowerShell Gallery |
```

2022-03-30 14:48 UTC, michaeltlombardi commented on reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md
> +| **Required**          | For PowerShell Gallery         |
```suggestion
| **Required**          | PowerShell Gallery         |
```

2022-03-30 14:52 UTC, opbld33 commented
Docs Build status updates of commit _[97c6119](https://github.com/michaeltlombardi/PowerShell-Docs/commits/97c6119ba244252bec5fbdd9e19f86941a8d7bf3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203301450265041-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T14%3A52%3A12Z&sr=b&sp=r&sig=Trz%2BOgsn5P52tUIB7WR8XZFN8kGbQ9S4ODFLqvrqqpQ%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 16:14 UTC, opbld30 commented
Docs Build status updates of commit _[f16e7f6](https://github.com/michaeltlombardi/PowerShell-Docs/commits/f16e7f6ac300f7eb0ab0fb14217c2a5961797400)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/5.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-5.1&branch=pr-en-us-8696) (powershell-5.1) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/7.0/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-7&branch=pr-en-us-8696) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/7.1/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-7.1&branch=pr-en-us-8696) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/7.2/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-7.2&branch=pr-en-us-8696) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifest.md](https://github.com/michaeltlombardi/PowerShell-Docs/blob/GH-8503/staging/about_module_manifests/reference/7.3/Microsoft.PowerShell.Core/About/about_Module_Manifest.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_module_manifest?view=powershell-7.3&branch=pr-en-us-8696) (powershell-7.3) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C3%5C30%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202203301612180839-8696%5Cworkflow_report.html?sv=2020-08-04&se=2022-04-30T16%3A14%3A33Z&sr=b&sp=r&sig=RCa2LdyCoaR9A5Ym7U0ONc6YHglhBA42KEyCiCJeBhM%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-03-30 19:28 UTC, sdwheeler approved these changes

2022-03-30 19:28 UTC, merged