Update asPowerShell spacing - closes #8755
MicrosoftDocs/PowerShell-Docs pull request #8779
Opened 2022-05-02 00:10 UTC by tommymaynard

# PR Summary

## PR Context

Check the boxes below to indicate the content affected by this PR.

**Repository or docset configuration**
- [ ] Repo documentation and configuration (.git/.github/.vscode etc.)
- [ ] Docs build files (.openpublishing.* and build scripts)
- [ ] Docset configuration (docfx.json, mapping, bread, module folder)

**Conceptual documentation**
- [ ] Files in docs-conceptual

**Cmdlet reference & about_ topics**
When changing **cmdlet reference** or **about_ topics**, the changes should be copied to all
relevant versions. Check the boxes below to indicate the versions affected by this change.

- [x] Preview content
- [x] Version 7.2 content
- [x] Version 7.1 content
- [x] Version 7.0 content
- [x] Version 5.1 content

## PR Checklist

- [x] I have read the [contributors guide][contrib] and followed the style and process guidelines
- [x] PR has a meaningful title
- [x] PR is targeted at the _staging_ branch
- [x] All relevant versions updated
- [x] Includes content related to issues and PRs - see [Closing issues using keywords][key].
- [x] This PR is ready to merge and is not **Work in Progress**. If the PR is work in progress,
  please add the prefix `WIP:` or `[WIP]` to the beginning of the title and remove the prefix when
  the PR is ready.

[contrib]: https://docs.microsoft.com/powershell/scripting/community/contributing/overview
[key]: https://help.github.com/en/articles/closing-issues-using-keywords

2022-05-02 00:13 UTC, opbld30 commented
Docs Build status updates of commit _[31d420d](https://github.com/tommymaynard/PowerShell-Docs/commits/31d420df0e6333e05ed0baf517ef3636ce42efc7)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/5.1/Microsoft.PowerShell.Core/About/about_Parsing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_parsing?view=powershell-5.1&branch=pr-en-us-8779) (powershell-5.1) |
[reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.0/Microsoft.PowerShell.Core/About/about_Parsing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7&branch=pr-en-us-8779) (powershell-7) |
[reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.1/Microsoft.PowerShell.Core/About/about_Parsing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.1&branch=pr-en-us-8779) (powershell-7.1) |
[reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.2/Microsoft.PowerShell.Core/About/about_Parsing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.2&branch=pr-en-us-8779) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md](https://github.com/MicrosoftDocs/PowerShell-Docs/blob/staging/reference/7.3/Microsoft.PowerShell.Core/About/about_Parsing.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/about/about_parsing?view=powershell-7.3&branch=pr-en-us-8779) (powershell-7.3) |

For more details, please refer to the [build report](https://opbuilduserstoragepublic.blob.core.windows.net/report/2022%5C5%5C2%5C6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f%5CPullRequest%5C202205020010571754-8779%5Cworkflow_report.html?sv=2021-04-10&se=2022-06-02T00%3A13%3A09Z&sr=b&sp=r&sig=PeUsfvLFJjb0Va4AVoBwDmmVPJM1RasrYB0rMjcN6ow%3D).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-05-02 17:23 UTC, sdwheeler requested changes
@tommymaynard The change looks good. Can you add a short description of the PR and add the comment to link the PR to the issue?

See https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

2022-05-02 19:10 UTC, tommymaynard commented
Hi @sdwheeler. Hopefully, this what you are after! This PR fixes a small spacing problem in about_Parsing for versions 5.1, 7.0, 7.1, 7.2, and 7.3. This PR is linked with issue #8755.

2022-05-02 19:14 UTC, sdwheeler commented
@tommymaynard Edit the original description and add that information under PR Summary. Use the `Fixes` keyword with the issue number so that the PR will close the issue when merged (as described in the doc I linked to).

2022-05-03 18:04 UTC, sdwheeler approved these changes

2022-05-03 18:04 UTC, merged