[BULK UPDATE] DocuTune - Fix build validation issues: docs-link-absolute (part 1)
MicrosoftDocs/PowerShell-Docs pull request #9196
Opened 2022-09-04 21:18 UTC by alexbuckgit

**Global effort to fix build validation errors**

The Microsoft Skilling team is fixing build validation errors and specific brand inconsistencies in Microsoft technical documentation for the rest of FY23 Q1. This will help address various accessibility, security, and usability issues. This PR was generated using DocuTune. It includes only targeted fixes and minor formatting adjustments.

DocuTune PRs improve quality of technical content by finding and automatically correcting a broad set of issues only where the correction is suitable. Please review within five business days and merge or comment in the PR with any changes you'd like to see. Thank you!

CorrelationId: 0df9c2d6-63f8-4d1e-8b57-b33611a06514
InitiativeId: docutune-build-validation-issues-2022-05
PointOfContact: Alex Buck

2022-09-04 21:18 UTC, alexbuckgit commented
#docutune-draft

2022-09-04 21:20 UTC, opbld31 commented
Docs Build status updates of commit _[3aed692](https://github.com/alexbuckgit/PowerShell-Docs/commits/3aed692d7f9f77e4df50f81ad46f217146b1da69)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[README.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/README.md) | :white_check_mark:Succeeded | |
[reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.localaccounts/new-localuser?view=powershell-5.1&branch=pr-en-us-9196) (powershell-5.1) |
[reference/docs-conceptual/community/2020-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2020-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2020-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2021-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2021-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2021-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2022-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2022-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2022-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/editorial-checklist.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/editorial-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/editorial-checklist?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/general-markdown.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/general-markdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/general-markdown?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/overview.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/overview?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202209042118208317-9196/BuildReport?accessString=a6734f84bd02a31401ac38ac3167e202a396033b220057302e7a765e270299b0).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 14:16 UTC, sdwheeler requested changes

2022-09-06 14:16 UTC, sdwheeler commented on README.md
> +  [PowerShell technical documentation](/powershell/scripting/). This includes both
The README is not published to Microsoft Docs so the URL shouldn't be changed. It must be fully-qualified to work in GitHub.

2022-09-06 19:34 UTC, sdwheeler approved these changes

2022-09-06 19:36 UTC, opbld32 commented
Docs Build status updates of commit _[cb86448](https://github.com/alexbuckgit/PowerShell-Docs/commits/cb8644835b425c8fab4452c6dc8ce3cdaf7e2ea8)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.localaccounts/new-localuser?view=powershell-5.1&branch=pr-en-us-9196) (powershell-5.1) |
[reference/docs-conceptual/community/2020-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2020-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2020-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2021-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2021-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2021-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2022-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2022-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2022-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/editorial-checklist.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/editorial-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/editorial-checklist?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/general-markdown.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/general-markdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/general-markdown?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/overview.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/overview?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202209061934262066-9196/BuildReport?accessString=4524cda5c5dfe57872aca46df232b7afab53cdb78dd6f89e0e0ea3e8bedef0d8).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 19:38 UTC, JustPies commented
#docutune-ready

2022-09-06 19:38 UTC, opbld31 commented
Docs Build status updates of commit _[aef44b4](https://github.com/alexbuckgit/PowerShell-Docs/commits/aef44b442a3f41e358613c14b2886e9305e0da82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/5.1/Microsoft.PowerShell.LocalAccounts/New-LocalUser.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/module/microsoft.powershell.localaccounts/new-localuser?view=powershell-5.1&branch=pr-en-us-9196) (powershell-5.1) |
[reference/docs-conceptual/community/2020-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2020-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2020-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2021-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2021-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2021-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/2022-updates.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/2022-updates.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/2022-updates?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/editorial-checklist.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/editorial-checklist.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/editorial-checklist?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/general-markdown.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/general-markdown.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/general-markdown?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |
[reference/docs-conceptual/community/contributing/overview.md](https://github.com/alexbuckgit/PowerShell-Docs/blob/alexbuckgit/docutune-autopr-docs-link-absolute-20220904-184118-1296187/reference/docs-conceptual/community/contributing/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/PowerShell/scripting/community/contributing/overview?view=powershell-7.x&branch=pr-en-us-9196) (>=powershell-5.1) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202209061934385080-9196/BuildReport?accessString=2a26568b9dc5ed1703b3c411425f2d9d3e964cd585e4ff2479d981114df28879).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

2022-09-06 19:49 UTC, merged