Fixes #9250 - Add article showing how to invoke a PSCmdlet
MicrosoftDocs/PowerShell-Docs pull request #9279
Opened 2022-10-06 20:55 UTC by sdwheeler

# PR Summary

Fixes AB#13011 - Fixes #9250 - Add article showing how to invoke a PSCmdlet

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2022-10-06 20:57 UTC, opbld30 commented
Learn Build status updates of commit _[0aa6c58](https://github.com/sdwheeler/PowerShell-Docs/commits/0aa6c58c2b4bb98ccbd550ba6de57921fadeda02)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062055219343-9279/BuildReport?accessString=e36dbdc4c4e89e02d8ffd148d0f11b10217a35ad93cb32c1631c47520df14433).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:03 UTC, opbld31 commented
Learn Build status updates of commit _[f98982d](https://github.com/sdwheeler/PowerShell-Docs/commits/f98982dc6fb8678f44521f4a5b65ad6bd0499919)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062101377081-9279/BuildReport?accessString=7c4ec2360035e94fc84cd80007af81332fdc812b08d3b0145bc4e9fc5e30cecf).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:05 UTC, opbld31 commented
Learn Build status updates of commit _[f0cedb3](https://github.com/sdwheeler/PowerShell-Docs/commits/f0cedb36bbc054dff9b6fcad837938eab8a3a6e0)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062102547476-9279/BuildReport?accessString=093a8b262446380e11ada9f9a31db7d774d2a794c979d350fddbc67f85071037).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:07 UTC, SteveL-MSFT requested changes

2022-10-06 21:12 UTC, opbld31 commented
Learn Build status updates of commit _[cc0e86c](https://github.com/sdwheeler/PowerShell-Docs/commits/cc0e86cad28057b1e9bd85f882de53cd277c1f82)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062110080530-9279/BuildReport?accessString=3b3111149590b172bf6bcbb471c6dae58671de7433683b8ea639220229f1342c).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:22 UTC, sdwheeler commented on reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md
> +
See the note I added.

2022-10-06 21:24 UTC, opbld30 commented
Learn Build status updates of commit _[72e9a2f](https://github.com/sdwheeler/PowerShell-Docs/commits/72e9a2fa5dae6e2ac707b8aa2c8b1676bb0a4943)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062122388135-9279/BuildReport?accessString=3ae356699636834443348d132131d456c4e36e332d39d2c786f49f0e7dae014b).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-06 21:29 UTC, SteveL-MSFT approved these changes
LGTM

2022-10-06 21:30 UTC, opbld32 commented
Learn Build status updates of commit _[cb65d24](https://github.com/sdwheeler/PowerShell-Docs/commits/cb65d247f25ad965908899da58f480af0fe6e7fd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210062128581912-9279/BuildReport?accessString=7d089480c5c9f93d42529af24e57eda9db2fbd92213d83f532c0eeb3a25de7aa).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 03:03 UTC, opbld33 commented
Learn Build status updates of commit _[ec744bc](https://github.com/sdwheeler/PowerShell-Docs/commits/ec744bc23bc5f845a00240f9cc2b89c9f48eeb04)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210070301356908-9279/BuildReport?accessString=253a30cb499f56ab0aa6437c41e6ea0a5745eba1de66479f2f44aaf70472a528).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 14:31 UTC, opbld32 commented
Learn Build status updates of commit _[5353658](https://github.com/sdwheeler/PowerShell-Docs/commits/5353658aaf04a92fd45176b697c0dca00508c6b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-cmdlet-from-within-a-cmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/scripting/developer/cmdlet/how-to-invoke-a-pscmdlet-from-within-a-pscmdlet?view=powershell-7.x&branch=pr-en-us-9279) (>=powershell-5.1) |
[reference/docs-conceptual/developer/toc.yml](https://github.com/sdwheeler/PowerShell-Docs/blob/sdw-i9250/reference/docs-conceptual/developer/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202210071429295334-9279/BuildReport?accessString=a7c16d20dba0a028f20d1d5a6046a319c43f4d6b1c0fe8c7d686f7c44447e548).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-07 15:08 UTC, merged

2022-10-20 18:06 UTC, MatejKafka commented
@sdwheeler In the article, the PowerShell class is used. From my tests, the invocation is quite slow that way. In the meantime, I found another way to invoke a PSCmdlet:
```powershell
function fn {
    [CmdletBinding()]param()
    $ss = $PSCmdlet.SessionState
    $ss.InvokeCommand.InvokeScript($ss, [ScriptBlock]::Create('Get-Clipboard -Raw'))
}
```
(it works the same from a C# binary cmdlet)

This way of invoking `Get-Clipboard` is about 5 times faster for me (2ms vs 10ms for the `PowerShell.Create` approach). Am I missing any downside of this approach?

2022-10-20 18:46 UTC, SeeminglyScience commented
> @sdwheeler In the article, the PowerShell class is used. From my tests, the invocation is quite slow that way. In the meantime, I found another way to invoke a PSCmdlet:
> 
> ```powershell
> function fn {
>     [CmdletBinding()]param()
>     $ss = $PSCmdlet.SessionState
>     $ss.InvokeCommand.InvokeScript($ss, [ScriptBlock]::Create('Get-Clipboard -Raw'))
> }
> ```
> 
> (it works the same from a C# binary cmdlet)
> 
> This way of invoking `Get-Clipboard` is about 5 times faster for me (2ms vs 10ms for the `PowerShell.Create` approach). Am I missing any downside of this approach?

The doc should be using `PowerShell.Create(RunspaceMode.CurrentRunspace)`. That's likely the problem you're hitting in your benchmark, because otherwise it spins up a new runspace for every invocation.

2022-10-20 20:14 UTC, MatejKafka commented
@SeeminglyScience 

With `RunspaceMode.CurrentRunspace`, it is significantly faster, but still slower than `InvokeScript`, which I find a bit surprising, given that `InvokeScript` has to first parse the script-block.

My naive benchmark code:
```csharp
using System.Diagnostics;
using System.Management.Automation;

namespace RandomTests;

[Cmdlet(VerbsDiagnostic.Test, "PSCmdlet")]
public class Test : PSCmdlet {
    public string PowerShellCreate() {
        var ps = PowerShell.Create(RunspaceMode.CurrentRunspace);
        ps.AddCommand("Get-Clipboard").AddParameter("-Raw");
        return ps.Invoke<string>()[0];
    }

    public string InvokeScript() {
        var sb = ScriptBlock.Create("Get-Clipboard -Raw");
        return (string)SessionState.InvokeCommand.InvokeScript(SessionState, sb)[0].BaseObject;
    }

    protected override void BeginProcessing() {
        base.BeginProcessing();
        var sw = new Stopwatch();
        sw.Start();
        for (var i = 0; i < 10000; i++) {
            PowerShellCreate();
        }
        sw.Stop();
        WriteObject($"PowerShellCreate: {sw.ElapsedMilliseconds}");
        sw.Restart();
        for (var i = 0; i < 10000; i++) {
            InvokeScript();
        }
        sw.Stop();
        WriteObject($"InvokeScript: {sw.ElapsedMilliseconds}");
    }
}
```

Results:
```
> for ($i = 0; $i -lt 10; $i++) {Test-PSCmdlet}
PowerShellCreate: 618
InvokeScript: 369
PowerShellCreate: 539
InvokeScript: 357
PowerShellCreate: 588
InvokeScript: 407
PowerShellCreate: 626
InvokeScript: 404
PowerShellCreate: 632
InvokeScript: 402
PowerShellCreate: 616
InvokeScript: 409
PowerShellCreate: 614
InvokeScript: 405
PowerShellCreate: 615
InvokeScript: 407
PowerShellCreate: 620
InvokeScript: 418
PowerShellCreate: 619
InvokeScript: 424
```

2022-10-20 20:53 UTC, SeeminglyScience commented
I'd use [BenchmarkDotNet](https://github.com/dotnet/BenchmarkDotNet) for the tests, but either way the `PowerShell` API will more consistent and typically more natural to use from C#.