Quality: Add alias to Notes section of Clear-Host and Out-Host Cmdlets
MicrosoftDocs/PowerShell-Docs pull request #9630
Opened 2022-12-31 05:12 UTC by szabolevo

# PR Summary

This adds alias information to the Notes section in the documentation for Clear-Host and Out-Host.

- Resolves #9629 

## PR Checklist

- [x] **Descriptive Title:** This PR's title is a synopsis of the changes it proposes.
- [x] **Summary:** This PR's summary describes the scope and intent of the change.
- [x] **Contributor's Guide:** I have read the [contributors guide][contrib].
- [x] **Style:** This PR adheres to the [style guide][style].

[contrib]: https://learn.microsoft.com/powershell/scripting/community/contributing/overview
[style]: https://learn.microsoft.com/powershell/scripting/community/contributing/powershell-style-guide

2022-12-31 05:15 UTC, opbld32 commented
Learn Build status updates of commit _[3d46b03](https://github.com/szabolevo/PowerShell-Docs_fork/commits/3d46b0324abd3d365da4168b42e79ab45f36738b)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.2/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.3/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |
[reference/7.4/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202212310512297221-9630/BuildReport?accessString=7ec5759e080d87d6403222044865d22783231b15fde52256a964fa2706ba272f).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-31 06:10 UTC, ehmiiz commented
Awesome PR! 🥳
Some feedback: be sure to edit the Ms.keydate value to the current date, (line 5 in the .med file), to inform others when changes was made to the docs. 
Happy new year's 🎈

2022-12-31 14:47 UTC, sdwheeler requested changes
@szabolevo Thanks for the PR.

Please accept the suggested changes and update the `ms.date` value at the top of each file.

2022-12-31 14:47 UTC, sdwheeler commented on reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md
> +- `cls`
```suggestion
- `clear`
- `cls`
```

2022-12-31 14:47 UTC, sdwheeler commented on reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md
> +  - `cls`
```suggestion
- Windows:
  - `clear`
  - `cls`

- Linux and macOS:
  - `cls`
```

2022-12-31 14:47 UTC, sdwheeler commented on reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md
> +  - `cls`
```suggestion
- Windows:
  - `clear`
  - `cls`

- Linux and macOS:
  - `cls`
```

2022-12-31 14:47 UTC, sdwheeler commented on reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md
> +  - `cls`
```suggestion
- Windows:
  - `clear`
  - `cls`

- Linux and macOS:
  - `cls`
```

2022-12-31 22:50 UTC, opbld30 commented
Learn Build status updates of commit _[7f72ba7](https://github.com/szabolevo/PowerShell-Docs_fork/commits/7f72ba7abb12e5fd7ed982c9a0b6369b761cc239)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.2/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.3/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |
[reference/7.4/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202212312248282583-9630/BuildReport?accessString=c8a1fc16d0526c4f761dd256e2e71aa3e79b13e721dcf61b4432cc8b9d0bdaa7).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-31 22:52 UTC, opbld31 commented
Learn Build status updates of commit _[09995cf](https://github.com/szabolevo/PowerShell-Docs_fork/commits/09995cf2bafeeee2d2d0d9824c2584ace8875126)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.2/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.3/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |
[reference/7.4/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202212312249395604-9630/BuildReport?accessString=c85b0ebebd43c2a526d9467dfb20c274f4d45d8cfd50964a5ec24059f8dcd77a).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-31 22:54 UTC, opbld33 commented
Learn Build status updates of commit _[68098a8](https://github.com/szabolevo/PowerShell-Docs_fork/commits/68098a8725acaf0fea12df823d4002ea1e9a31b4)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.2/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.3/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |
[reference/7.4/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202212312250456629-9630/BuildReport?accessString=4f28c899985607ea00928890d2befc3ff0cff94f7760856a58991cee425f8cea).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-31 23:00 UTC, opbld30 commented
Learn Build status updates of commit _[5a6a952](https://github.com/szabolevo/PowerShell-Docs_fork/commits/5a6a9526fdfcbda22d387b133310949adfcdf76a)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/5.1/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/5.1/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-5.1&branch=pr-en-us-9630) (powershell-5.1) |
[reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.2/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.2/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.2&branch=pr-en-us-9630) (powershell-7.2) |
[reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.3/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.3/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.3&branch=pr-en-us-9630) (powershell-7.3) |
[reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Clear-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/clear-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |
[reference/7.4/Microsoft.PowerShell.Core/Out-Host.md](https://github.com/szabolevo/PowerShell-Docs_fork/blob/main/reference/7.4/Microsoft.PowerShell.Core/Out-Host.md) | :white_check_mark:Succeeded | [View](https://review.learn.microsoft.com/en-us/PowerShell/module/microsoft.powershell.core/out-host?view=powershell-7.4&branch=pr-en-us-9630) (powershell-7.4) |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f/202212312258345177-9630/BuildReport?accessString=7d92f42778683d0531e11495dbdb7e3f5c036f0d5c13d022255bbe295bde0cb4).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/6ff7e8c3-dfc6-3ebd-da5a-d5e2ff43de8f?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-12-31 23:16 UTC, szabolevo commented
Thanks @ehmiiz  and @sdwheeler  for the feedback, fixed both recommendations. Happy New Year!

2023-01-01 15:31 UTC, sdwheeler approved these changes

2023-01-01 15:31 UTC, merged